spring:
  datasource:
    url: jdbc:h2:mem:db
    password: ''
    username: sa
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    # By default, the data.sql script executes before Hibernate initialization
    defer-datasource-initialization: true