INSERT INTO SYSTEM_PARAM (PARAM_CATEGORY, PARAM_KEY, PARAM_VALUE, PARAM_MEMO)
VALUES ('APP', 'KEY1', 'VALUE1', 'MEMO1');
INSERT INTO SYSTEM_PARAM (PARAM_CATEGORY, PARAM_KEY, PARAM_VALUE, PARAM_MEMO)
VALUES ('APP', 'KEY2', 'VALUE2', 'MEMO2');
INSERT INTO SYSTEM_PARAM (PARAM_CATEGORY, PARAM_KEY, PARAM_VALUE, PARAM_MEMO)
VALUES ('APP', 'KEY3', 'VALUE3', 'MEMO3');
INSERT INTO SYSTEM_PARAM (PARAM_CATEGORY, PARAM_KEY, PARAM_VALUE, PARAM_MEMO)
VALUES ('APP', 'KEY4', 'VALUE4', 'MEMO4');
